name: Build

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version: [ 8.1, 8.2, 8.3 ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        run: composer install --dev
      - name: Change permissions for phpcs
        run: chmod 755 build/vendor/bin/phpcs
      - name: Run WordPress code standard
        run: |
          ./build/vendor/bin/phpcs -v --ignore=vendor,build,tests,wpcs,scoper.inc.php --standard=./phpcs.xml ./
